modLoader="javafml"
license="${mod_license}"
loaderVersion="${loader_version_range}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
authors="ChinaEX123,Fvue233"
description='''
Add small features to Tide.
'''

[[mixins]]
config="fintastic_supreme.mixins.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="tide"
    type="required"
    versionRange="[2.0.3,)"
    ordering="AFTER"
    side="BOTH"
